title: "Mathématiques — Rudasingwa Ibrahim"
description: "Cours et ressources pédagogiques"
lang: fr

# IMPORTANT : pour un site utilisateur github.io
url: "https://rudasingwaibrahim.github.io"
baseurl: ""

markdown: kramdown
permalink: pretty

# On n'utilise pas de thème automatique
theme: null

# On inclut les dossiers utiles
include:
  - _pages

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
