title: "Mathématiques"
description: "Ressources, cours, devoirs et corrigés"
url: "https://rudasingwaibrahim.github.io"
theme: null

markdown: kramdown

school_name: "Lycée Younoussa Bamana"
school_address: "—"
school_city: "Mamoudzou, Mayotte"

contact_name: "Ibrahim Rudasingwa"
contact_email: "brhmrudasingwa@gmail.com"
